version: "3"
services:
    app:
        container_name: docker-node-mongo
        restart: always
        build: 
            context: ./backend/
            dockerfile: ./backend/Dockerfile
        ports:
            - '4000:4000'
        external_links:
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:27017"

    react-app:
        container_name: react-app
        build:
        context: ./frontend/
        dockerfile: ./frontend/Dockerfile
        ports:
            - '3000:3000'
        # command: "npm run serve"
        links:
            - "app"